Add site build check and avatar image
This commit adds a check to ensure that the site build is successful and includes a new avatar image.

diff --git a/.github/workflows/pages-deploy.yml b/.github/workflows/pages-deploy.yml
--- a/.github/workflows/pages-deploy.yml
+++ b/.github/workflows/pages-deploy.yml
@@ -50,6 +50,13 @@ jobs:
         env:
           JEKYLL_ENV: "production"
 
+      - name: Check site
+        run: |
+          if [ ! -f "_site/blog/index.html" ]; then
+            echo "Site build failed."
+            exit 1
+          fi
+      
       - name: Upload site artifact
         uses: actions/upload-pages-artifact@v1
         with:
